// What Poll says, in the 21 languages of the app (Plan §84). English is the source. The plugin's
// name is never written here: it comes from the manifest through the `{app}` hole. Days are
// formatted with `Intl` (`dates.js`) before they fill `{day}`; numbers with `Intl` too. No emoji:
// the view draws Ionicons beside the texts, and the ✅ of the chat summary comes through `{mark}`.

export const STRINGS = {
  en: {
    title: "Polls",
    close: "Close",
    back: "Back",
    kindDates: "Dates",
    kindText: "Options",
    questionPlaceholder: "Question, e.g. When shall we meet?",
    create: "Create the poll",
    empty: "No polls yet",
    shared: "Shared",
    closedTag: "Closed",
    delete: "Delete",
    confirmDelete: "Delete “{name}” from this phone? The other person keeps their copy.",
    cancel: "Cancel",
    pickDays: "Tap the days you propose.",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    addPlaceholder: "Add an option",
    add: "Add",
    remove: "Remove",
    yes: "Works for me",
    maybe: "Maybe",
    no: "Doesn't work for me",
    theirAnswer: "The other person: {answer}",
    theyHaventAnswered: "The other person hasn't answered yet",
    goodForBoth: "Good for both",
    closePoll: "Close the poll",
    chooseHint: "Choose the option the poll closes with.",
    choose: "Choose",
    confirmClose: "Close the poll with “{option}”? Nobody can vote after that.",
    onlyCreator: "Only the person who created the poll can close it.",
    chosen: "Chosen: {option}",
    send: "Put the result in the chat",
    icsSave: "Save to the calendar",
    icsSend: "Send the calendar event to the chat",
    icsSaved: "Saved on this phone. Open the file to add it to your calendar.",
    icsFailed: "The file could not be saved.",
    live: "Live",
    stopLive: "Stop live",
    waiting: "Waiting for the other person…",
    joined: "Live: you are both on this poll",
    silent: "The other person doesn't have {app} open in this conversation. They may not have it, may not have allowed it, or may have it closed.",
    unreachable: "The other phone can't be reached right now.",
    left: "The other person doesn't have the poll open any more.",
    outdated: "The other person has a newer {app}. Update {app} to vote together.",
    kept: "Your votes stay on this phone and join theirs when you both have the poll open in this conversation.",
    liveHint: "Live joins your votes only while you both have this poll open in this conversation.",
    needsChat: "To vote together, open {app} from a conversation and allow it to go live.",
    joinPrompt: "The other person opened “{name}”",
    join: "Join",
    notNow: "Not now",
    localHome: "Opened outside a conversation: these polls stay on this phone. A poll you share lives in its conversation.",
    received: "Shared poll",
    loading: "Waiting for the poll from the other person…",
    full: "No room left on this phone: the latest changes are not saved. Delete a poll to make room.",
    readOnly: "This poll comes from a newer {app}: update it to vote.",
    decidedDate: "Let's meet on {day}",
    both: "({mark} both)",
    everyone: "({mark} everyone)",
    some: "({mark} {yes} of {total})",
  },
  es: {
    title: "Encuestas",
    close: "Cerrar",
    back: "Atrás",
    kindDates: "Fechas",
    kindText: "Opciones",
    questionPlaceholder: "Pregunta, p. ej. ¿Cuándo quedamos?",
    create: "Crear la encuesta",
    empty: "Todavía no hay encuestas",
    shared: "Compartida",
    closedTag: "Cerrada",
    delete: "Borrar",
    confirmDelete: "¿Borrar «{name}» de este teléfono? La otra persona conserva su copia.",
    cancel: "Cancelar",
    pickDays: "Toca los días que propones.",
    previousMonth: "Mes anterior",
    nextMonth: "Mes siguiente",
    addPlaceholder: "Añadir una opción",
    add: "Añadir",
    remove: "Quitar",
    yes: "Me va bien",
    maybe: "Quizá",
    no: "No me va bien",
    theirAnswer: "La otra persona: {answer}",
    theyHaventAnswered: "La otra persona aún no ha respondido",
    goodForBoth: "Va bien a los dos",
    closePoll: "Cerrar la encuesta",
    chooseHint: "Elige la opción con la que se cierra la encuesta.",
    choose: "Elegir",
    confirmClose: "¿Cerrar la encuesta con «{option}»? Después nadie podrá votar.",
    onlyCreator: "Solo quien creó la encuesta puede cerrarla.",
    chosen: "Elegida: {option}",
    send: "Poner el resultado en el chat",
    icsSave: "Guardar en el calendario",
    icsSend: "Enviar el evento de calendario al chat",
    icsSaved: "Guardado en este teléfono. Abre el fichero para añadirlo a tu calendario.",
    icsFailed: "No se ha podido guardar el fichero.",
    live: "En directo",
    stopLive: "Parar el directo",
    waiting: "Esperando a la otra persona…",
    joined: "En directo: estáis los dos en esta encuesta",
    silent: "La otra persona no tiene {app} abierto en esta conversación. Puede que no lo tenga, que no le haya dado permiso o que lo tenga cerrado.",
    unreachable: "Ahora no se puede llegar al otro teléfono.",
    left: "La otra persona ya no tiene la encuesta abierta.",
    outdated: "La otra persona tiene un {app} más nuevo. Actualiza {app} para votar juntos.",
    kept: "Tus votos se quedan en este teléfono y se juntan con los suyos cuando los dos tengáis la encuesta abierta en esta conversación.",
    liveHint: "El directo junta vuestros votos solo mientras los dos tengáis esta encuesta abierta en esta conversación.",
    needsChat: "Para votar juntos, abre {app} desde una conversación, con el directo permitido.",
    joinPrompt: "La otra persona abrió «{name}»",
    join: "Unirse",
    notNow: "Ahora no",
    localHome: "Abierto fuera de una conversación: estas encuestas se quedan en este teléfono. Una encuesta compartida vive en su conversación.",
    received: "Encuesta compartida",
    loading: "Esperando la encuesta de la otra persona…",
    full: "No queda sitio en este teléfono: los últimos cambios no se han guardado. Borra una encuesta para hacer sitio.",
    readOnly: "Esta encuesta viene de un {app} más nuevo: actualízalo para votar.",
    decidedDate: "Quedamos el {day}",
    both: "({mark} los dos)",
    everyone: "({mark} todos)",
    some: "({mark} {yes} de {total})",
  },
  fr: {
    title: "Sondages",
    close: "Fermer",
    back: "Retour",
    kindDates: "Dates",
    kindText: "Options",
    questionPlaceholder: "Question, p. ex. Quand se voit-on ?",
    create: "Créer le sondage",
    empty: "Pas encore de sondage",
    shared: "Partagé",
    closedTag: "Clos",
    delete: "Supprimer",
    confirmDelete: "Supprimer « {name} » de ce téléphone ? L’autre personne garde sa copie.",
    cancel: "Annuler",
    pickDays: "Touchez les jours que vous proposez.",
    previousMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    addPlaceholder: "Ajouter une option",
    add: "Ajouter",
    remove: "Retirer",
    yes: "Ça me va",
    maybe: "Peut-être",
    no: "Ça ne me va pas",
    theirAnswer: "L’autre personne : {answer}",
    theyHaventAnswered: "L’autre personne n’a pas encore répondu",
    goodForBoth: "Ça va aux deux",
    closePoll: "Clore le sondage",
    chooseHint: "Choisissez l’option avec laquelle le sondage se clôt.",
    choose: "Choisir",
    confirmClose: "Clore le sondage avec « {option} » ? Personne ne pourra plus voter.",
    onlyCreator: "Seule la personne qui a créé le sondage peut le clore.",
    chosen: "Choisi : {option}",
    send: "Mettre le résultat dans la discussion",
    icsSave: "Enregistrer dans le calendrier",
    icsSend: "Envoyer l’événement de calendrier dans la discussion",
    icsSaved: "Enregistré sur ce téléphone. Ouvrez le fichier pour l’ajouter à votre calendrier.",
    icsFailed: "Impossible d’enregistrer le fichier.",
    live: "En direct",
    stopLive: "Arrêter le direct",
    waiting: "En attente de l’autre personne…",
    joined: "En direct : vous êtes tous les deux sur ce sondage",
    silent: "L’autre personne n’a pas {app} ouvert dans cette conversation. Elle ne l’a peut-être pas, ne l’a peut-être pas autorisé, ou l’a peut-être fermé.",
    unreachable: "L’autre téléphone est injoignable pour le moment.",
    left: "L’autre personne n’a plus le sondage ouvert.",
    outdated: "L’autre personne a une version plus récente de {app}. Mettez {app} à jour pour voter ensemble.",
    kept: "Vos votes restent sur ce téléphone et rejoignent les siens quand vous avez tous les deux le sondage ouvert dans cette conversation.",
    liveHint: "Le direct réunit vos votes seulement tant que vous avez tous les deux ce sondage ouvert dans cette conversation.",
    needsChat: "Pour voter ensemble, ouvrez {app} depuis une conversation, avec le direct autorisé.",
    joinPrompt: "L’autre personne a ouvert « {name} »",
    join: "Rejoindre",
    notNow: "Plus tard",
    localHome: "Ouvert hors d’une conversation : ces sondages restent sur ce téléphone. Un sondage partagé vit dans sa conversation.",
    received: "Sondage partagé",
    loading: "En attente du sondage de l’autre personne…",
    full: "Plus de place sur ce téléphone : les dernières modifications ne sont pas enregistrées. Supprimez un sondage pour faire de la place.",
    readOnly: "Ce sondage vient d’une version plus récente de {app} : mettez-le à jour pour voter.",
    decidedDate: "On se voit le {day}",
    both: "({mark} tous les deux)",
    everyone: "({mark} tout le monde)",
    some: "({mark} {yes} sur {total})",
  },
  de: {
    title: "Umfragen",
    close: "Schließen",
    back: "Zurück",
    kindDates: "Termine",
    kindText: "Optionen",
    questionPlaceholder: "Frage, z. B. Wann treffen wir uns?",
    create: "Umfrage erstellen",
    empty: "Noch keine Umfragen",
    shared: "Geteilt",
    closedTag: "Beendet",
    delete: "Löschen",
    confirmDelete: "„{name}“ von diesem Telefon löschen? Die andere Person behält ihre Kopie.",
    cancel: "Abbrechen",
    pickDays: "Tippe auf die Tage, die du vorschlägst.",
    previousMonth: "Vorheriger Monat",
    nextMonth: "Nächster Monat",
    addPlaceholder: "Option hinzufügen",
    add: "Hinzufügen",
    remove: "Entfernen",
    yes: "Passt mir",
    maybe: "Vielleicht",
    no: "Passt mir nicht",
    theirAnswer: "Die andere Person: {answer}",
    theyHaventAnswered: "Die andere Person hat noch nicht geantwortet",
    goodForBoth: "Passt beiden",
    closePoll: "Umfrage beenden",
    chooseHint: "Wähle die Option, mit der die Umfrage endet.",
    choose: "Wählen",
    confirmClose: "Umfrage mit „{option}“ beenden? Danach kann niemand mehr abstimmen.",
    onlyCreator: "Nur wer die Umfrage erstellt hat, kann sie beenden.",
    chosen: "Gewählt: {option}",
    send: "Ergebnis in den Chat setzen",
    icsSave: "Im Kalender speichern",
    icsSend: "Kalendertermin in den Chat senden",
    icsSaved: "Auf diesem Telefon gespeichert. Öffne die Datei, um sie deinem Kalender hinzuzufügen.",
    icsFailed: "Die Datei konnte nicht gespeichert werden.",
    live: "Live",
    stopLive: "Live beenden",
    waiting: "Warten auf die andere Person…",
    joined: "Live: Ihr seid beide in dieser Umfrage",
    silent: "Die andere Person hat {app} in dieser Unterhaltung nicht geöffnet. Vielleicht hat sie es nicht, hat es nicht erlaubt oder hat es geschlossen.",
    unreachable: "Das andere Telefon ist gerade nicht erreichbar.",
    left: "Die andere Person hat die Umfrage nicht mehr offen.",
    outdated: "Die andere Person hat ein neueres {app}. Aktualisiere {app}, um gemeinsam abzustimmen.",
    kept: "Deine Stimmen bleiben auf diesem Telefon und kommen mit ihren zusammen, wenn ihr beide die Umfrage in dieser Unterhaltung geöffnet habt.",
    liveHint: "Live führt eure Stimmen nur zusammen, solange ihr beide diese Umfrage in dieser Unterhaltung geöffnet habt.",
    needsChat: "Um gemeinsam abzustimmen, öffne {app} aus einer Unterhaltung, mit erlaubtem Live-Modus.",
    joinPrompt: "Die andere Person hat „{name}“ geöffnet",
    join: "Beitreten",
    notNow: "Nicht jetzt",
    localHome: "Außerhalb einer Unterhaltung geöffnet: Diese Umfragen bleiben auf diesem Telefon. Eine geteilte Umfrage lebt in ihrer Unterhaltung.",
    received: "Geteilte Umfrage",
    loading: "Warten auf die Umfrage der anderen Person…",
    full: "Kein Platz mehr auf diesem Telefon: Die letzten Änderungen sind nicht gespeichert. Lösche eine Umfrage, um Platz zu schaffen.",
    readOnly: "Diese Umfrage stammt aus einem neueren {app}: Aktualisiere es, um abzustimmen.",
    decidedDate: "Wir treffen uns am {day}",
    both: "({mark} beide)",
    everyone: "({mark} alle)",
    some: "({mark} {yes} von {total})",
  },
  it: {
    title: "Sondaggi",
    close: "Chiudi",
    back: "Indietro",
    kindDates: "Date",
    kindText: "Opzioni",
    questionPlaceholder: "Domanda, es. Quando ci vediamo?",
    create: "Crea il sondaggio",
    empty: "Ancora nessun sondaggio",
    shared: "Condiviso",
    closedTag: "Chiuso",
    delete: "Elimina",
    confirmDelete: "Eliminare «{name}» da questo telefono? L’altra persona conserva la sua copia.",
    cancel: "Annulla",
    pickDays: "Tocca i giorni che proponi.",
    previousMonth: "Mese precedente",
    nextMonth: "Mese successivo",
    addPlaceholder: "Aggiungi un’opzione",
    add: "Aggiungi",
    remove: "Rimuovi",
    yes: "Mi va bene",
    maybe: "Forse",
    no: "Non mi va bene",
    theirAnswer: "L’altra persona: {answer}",
    theyHaventAnswered: "L’altra persona non ha ancora risposto",
    goodForBoth: "Va bene a entrambi",
    closePoll: "Chiudi il sondaggio",
    chooseHint: "Scegli l’opzione con cui si chiude il sondaggio.",
    choose: "Scegli",
    confirmClose: "Chiudere il sondaggio con «{option}»? Dopo nessuno potrà votare.",
    onlyCreator: "Solo chi ha creato il sondaggio può chiuderlo.",
    chosen: "Scelta: {option}",
    send: "Metti il risultato nella chat",
    icsSave: "Salva nel calendario",
    icsSend: "Invia l’evento del calendario nella chat",
    icsSaved: "Salvato su questo telefono. Apri il file per aggiungerlo al tuo calendario.",
    icsFailed: "Impossibile salvare il file.",
    live: "In diretta",
    stopLive: "Ferma la diretta",
    waiting: "In attesa dell’altra persona…",
    joined: "In diretta: siete entrambi su questo sondaggio",
    silent: "L’altra persona non ha {app} aperto in questa conversazione. Forse non ce l’ha, non l’ha autorizzato o l’ha chiuso.",
    unreachable: "L’altro telefono non è raggiungibile in questo momento.",
    left: "L’altra persona non ha più il sondaggio aperto.",
    outdated: "L’altra persona ha una versione più recente di {app}. Aggiorna {app} per votare insieme.",
    kept: "I tuoi voti restano su questo telefono e si uniscono ai suoi quando avete entrambi il sondaggio aperto in questa conversazione.",
    liveHint: "La diretta unisce i vostri voti solo mentre avete entrambi questo sondaggio aperto in questa conversazione.",
    needsChat: "Per votare insieme, apri {app} da una conversazione, con la diretta consentita.",
    joinPrompt: "L’altra persona ha aperto «{name}»",
    join: "Unisciti",
    notNow: "Non ora",
    localHome: "Aperto fuori da una conversazione: questi sondaggi restano su questo telefono. Un sondaggio condiviso vive nella sua conversazione.",
    received: "Sondaggio condiviso",
    loading: "In attesa del sondaggio dell’altra persona…",
    full: "Non c’è più spazio su questo telefono: le ultime modifiche non sono salvate. Elimina un sondaggio per fare spazio.",
    readOnly: "Questo sondaggio viene da una versione più recente di {app}: aggiornalo per votare.",
    decidedDate: "Ci vediamo {day}",
    both: "({mark} entrambi)",
    everyone: "({mark} tutti)",
    some: "({mark} {yes} su {total})",
  },
  pt: {
    title: "Sondagens",
    close: "Fechar",
    back: "Voltar",
    kindDates: "Datas",
    kindText: "Opções",
    questionPlaceholder: "Pergunta, p. ex. Quando nos encontramos?",
    create: "Criar a sondagem",
    empty: "Ainda não há sondagens",
    shared: "Partilhada",
    closedTag: "Fechada",
    delete: "Apagar",
    confirmDelete: "Apagar «{name}» deste telemóvel? A outra pessoa fica com a sua cópia.",
    cancel: "Cancelar",
    pickDays: "Toque nos dias que propõe.",
    previousMonth: "Mês anterior",
    nextMonth: "Mês seguinte",
    addPlaceholder: "Adicionar uma opção",
    add: "Adicionar",
    remove: "Remover",
    yes: "Dá-me jeito",
    maybe: "Talvez",
    no: "Não me dá jeito",
    theirAnswer: "A outra pessoa: {answer}",
    theyHaventAnswered: "A outra pessoa ainda não respondeu",
    goodForBoth: "Dá jeito aos dois",
    closePoll: "Fechar a sondagem",
    chooseHint: "Escolha a opção com que a sondagem fecha.",
    choose: "Escolher",
    confirmClose: "Fechar a sondagem com «{option}»? Depois ninguém poderá votar.",
    onlyCreator: "Só quem criou a sondagem a pode fechar.",
    chosen: "Escolhida: {option}",
    send: "Pôr o resultado na conversa",
    icsSave: "Guardar no calendário",
    icsSend: "Enviar o evento do calendário para a conversa",
    icsSaved: "Guardado neste telemóvel. Abra o ficheiro para o adicionar ao seu calendário.",
    icsFailed: "Não foi possível guardar o ficheiro.",
    live: "Em direto",
    stopLive: "Parar o direto",
    waiting: "À espera da outra pessoa…",
    joined: "Em direto: estão os dois nesta sondagem",
    silent: "A outra pessoa não tem o {app} aberto nesta conversa. Pode não o ter, não lhe ter dado permissão ou tê-lo fechado.",
    unreachable: "Agora não é possível chegar ao outro telemóvel.",
    left: "A outra pessoa já não tem a sondagem aberta.",
    outdated: "A outra pessoa tem um {app} mais recente. Atualize o {app} para votarem juntos.",
    kept: "Os seus votos ficam neste telemóvel e juntam-se aos da outra pessoa quando os dois tiverem a sondagem aberta nesta conversa.",
    liveHint: "O direto junta os vossos votos só enquanto os dois tiverem esta sondagem aberta nesta conversa.",
    needsChat: "Para votarem juntos, abra o {app} a partir de uma conversa, com o direto permitido.",
    joinPrompt: "A outra pessoa abriu «{name}»",
    join: "Entrar",
    notNow: "Agora não",
    localHome: "Aberto fora de uma conversa: estas sondagens ficam neste telemóvel. Uma sondagem partilhada vive na sua conversa.",
    received: "Sondagem partilhada",
    loading: "À espera da sondagem da outra pessoa…",
    full: "Não há espaço neste telemóvel: as últimas alterações não foram guardadas. Apague uma sondagem para libertar espaço.",
    readOnly: "Esta sondagem vem de um {app} mais recente: atualize-o para votar.",
    decidedDate: "Fica marcado: {day}",
    both: "({mark} os dois)",
    everyone: "({mark} todos)",
    some: "({mark} {yes} de {total})",
  },
  ro: {
    title: "Sondaje",
    close: "Închide",
    back: "Înapoi",
    kindDates: "Date",
    kindText: "Opțiuni",
    questionPlaceholder: "Întrebare, de ex. Când ne vedem?",
    create: "Creează sondajul",
    empty: "Încă nu există sondaje",
    shared: "Partajat",
    closedTag: "Închis",
    delete: "Șterge",
    confirmDelete: "Ștergi „{name}” de pe acest telefon? Cealaltă persoană își păstrează copia.",
    cancel: "Anulează",
    pickDays: "Atinge zilele pe care le propui.",
    previousMonth: "Luna anterioară",
    nextMonth: "Luna următoare",
    addPlaceholder: "Adaugă o opțiune",
    add: "Adaugă",
    remove: "Elimină",
    yes: "Îmi convine",
    maybe: "Poate",
    no: "Nu îmi convine",
    theirAnswer: "Cealaltă persoană: {answer}",
    theyHaventAnswered: "Cealaltă persoană nu a răspuns încă",
    goodForBoth: "Convine amândurora",
    closePoll: "Închide sondajul",
    chooseHint: "Alege opțiunea cu care se închide sondajul.",
    choose: "Alege",
    confirmClose: "Închizi sondajul cu „{option}”? După asta nimeni nu mai poate vota.",
    onlyCreator: "Doar cine a creat sondajul îl poate închide.",
    chosen: "Ales: {option}",
    send: "Pune rezultatul în conversație",
    icsSave: "Salvează în calendar",
    icsSend: "Trimite evenimentul din calendar în conversație",
    icsSaved: "Salvat pe acest telefon. Deschide fișierul ca să-l adaugi în calendar.",
    icsFailed: "Fișierul nu a putut fi salvat.",
    live: "În direct",
    stopLive: "Oprește modul în direct",
    waiting: "Se așteaptă cealaltă persoană…",
    joined: "În direct: sunteți amândoi în acest sondaj",
    silent: "Cealaltă persoană nu are {app} deschis în această conversație. Poate nu îl are, nu i-a dat permisiunea sau l-a închis.",
    unreachable: "Celălalt telefon nu poate fi contactat acum.",
    left: "Cealaltă persoană nu mai are sondajul deschis.",
    outdated: "Cealaltă persoană are o versiune mai nouă de {app}. Actualizează {app} ca să votați împreună.",
    kept: "Voturile tale rămân pe acest telefon și se unesc cu ale ei când aveți amândoi sondajul deschis în această conversație.",
    liveHint: "Modul în direct vă unește voturile doar cât timp aveți amândoi acest sondaj deschis în această conversație.",
    needsChat: "Ca să votați împreună, deschide {app} dintr-o conversație, cu modul în direct permis.",
    joinPrompt: "Cealaltă persoană a deschis „{name}”",
    join: "Alătură-te",
    notNow: "Nu acum",
    localHome: "Deschis în afara unei conversații: aceste sondaje rămân pe acest telefon. Un sondaj partajat trăiește în conversația lui.",
    received: "Sondaj partajat",
    loading: "Se așteaptă sondajul celeilalte persoane…",
    full: "Nu mai e loc pe acest telefon: ultimele modificări nu sunt salvate. Șterge un sondaj ca să faci loc.",
    readOnly: "Acest sondaj vine dintr-o versiune mai nouă de {app}: actualizează-l ca să votezi.",
    decidedDate: "Ne vedem {day}",
    both: "({mark} amândoi)",
    everyone: "({mark} toți)",
    some: "({mark} {yes} din {total})",
  },
  pl: {
    title: "Ankiety",
    close: "Zamknij",
    back: "Wstecz",
    kindDates: "Terminy",
    kindText: "Opcje",
    questionPlaceholder: "Pytanie, np. Kiedy się spotkamy?",
    create: "Utwórz ankietę",
    empty: "Nie ma jeszcze ankiet",
    shared: "Udostępniona",
    closedTag: "Zamknięta",
    delete: "Usuń",
    confirmDelete: "Usunąć „{name}” z tego telefonu? Druga osoba zachowa swoją kopię.",
    cancel: "Anuluj",
    pickDays: "Dotknij dni, które proponujesz.",
    previousMonth: "Poprzedni miesiąc",
    nextMonth: "Następny miesiąc",
    addPlaceholder: "Dodaj opcję",
    add: "Dodaj",
    remove: "Usuń opcję",
    yes: "Pasuje mi",
    maybe: "Może",
    no: "Nie pasuje mi",
    theirAnswer: "Druga osoba: {answer}",
    theyHaventAnswered: "Druga osoba jeszcze nie odpowiedziała",
    goodForBoth: "Pasuje obojgu",
    closePoll: "Zamknij ankietę",
    chooseHint: "Wybierz opcję, z którą ankieta się zamknie.",
    choose: "Wybierz",
    confirmClose: "Zamknąć ankietę z wyborem „{option}”? Potem nikt nie będzie mógł głosować.",
    onlyCreator: "Tylko osoba, która utworzyła ankietę, może ją zamknąć.",
    chosen: "Wybrano: {option}",
    send: "Wstaw wynik do czatu",
    icsSave: "Zapisz w kalendarzu",
    icsSend: "Wyślij wydarzenie kalendarza do czatu",
    icsSaved: "Zapisano na tym telefonie. Otwórz plik, aby dodać go do kalendarza.",
    icsFailed: "Nie udało się zapisać pliku.",
    live: "Na żywo",
    stopLive: "Zakończ tryb na żywo",
    waiting: "Czekanie na drugą osobę…",
    joined: "Na żywo: oboje jesteście w tej ankiecie",
    silent: "Druga osoba nie ma otwartej aplikacji {app} w tej rozmowie. Może jej nie mieć, mogła nie dać zgody albo ją zamknęła.",
    unreachable: "Nie można teraz połączyć się z drugim telefonem.",
    left: "Druga osoba nie ma już otwartej ankiety.",
    outdated: "Druga osoba ma nowszą wersję {app}. Zaktualizuj {app}, aby głosować razem.",
    kept: "Twoje głosy zostają na tym telefonie i połączą się z jej głosami, gdy oboje będziecie mieć ankietę otwartą w tej rozmowie.",
    liveHint: "Tryb na żywo łączy wasze głosy tylko wtedy, gdy oboje macie tę ankietę otwartą w tej rozmowie.",
    needsChat: "Aby głosować razem, otwórz {app} z rozmowy, z dozwolonym trybem na żywo.",
    joinPrompt: "Druga osoba otworzyła „{name}”",
    join: "Dołącz",
    notNow: "Nie teraz",
    localHome: "Otwarte poza rozmową: te ankiety zostają na tym telefonie. Udostępniona ankieta żyje w swojej rozmowie.",
    received: "Udostępniona ankieta",
    loading: "Czekanie na ankietę od drugiej osoby…",
    full: "Brak miejsca na tym telefonie: ostatnie zmiany nie są zapisane. Usuń ankietę, aby zrobić miejsce.",
    readOnly: "Ta ankieta pochodzi z nowszej wersji {app}: zaktualizuj ją, aby głosować.",
    decidedDate: "Widzimy się: {day}",
    both: "({mark} oboje)",
    everyone: "({mark} wszyscy)",
    some: "({mark} {yes} z {total})",
  },
  ru: {
    title: "Опросы",
    close: "Закрыть",
    back: "Назад",
    kindDates: "Даты",
    kindText: "Варианты",
    questionPlaceholder: "Вопрос, например: Когда встретимся?",
    create: "Создать опрос",
    empty: "Опросов пока нет",
    shared: "Общий",
    closedTag: "Завершён",
    delete: "Удалить",
    confirmDelete: "Удалить «{name}» с этого телефона? У другого человека останется его копия.",
    cancel: "Отмена",
    pickDays: "Нажмите на дни, которые предлагаете.",
    previousMonth: "Предыдущий месяц",
    nextMonth: "Следующий месяц",
    addPlaceholder: "Добавить вариант",
    add: "Добавить",
    remove: "Убрать",
    yes: "Мне подходит",
    maybe: "Возможно",
    no: "Мне не подходит",
    theirAnswer: "Другой человек: {answer}",
    theyHaventAnswered: "Другой человек ещё не ответил",
    goodForBoth: "Подходит обоим",
    closePoll: "Завершить опрос",
    chooseHint: "Выберите вариант, с которым опрос завершится.",
    choose: "Выбрать",
    confirmClose: "Завершить опрос с вариантом «{option}»? После этого никто не сможет голосовать.",
    onlyCreator: "Завершить опрос может только тот, кто его создал.",
    chosen: "Выбрано: {option}",
    send: "Вставить результат в чат",
    icsSave: "Сохранить в календарь",
    icsSend: "Отправить событие календаря в чат",
    icsSaved: "Сохранено на этом телефоне. Откройте файл, чтобы добавить его в календарь.",
    icsFailed: "Не удалось сохранить файл.",
    live: "Вместе",
    stopLive: "Закончить совместную работу",
    waiting: "Ждём другого человека…",
    joined: "Вместе: вы оба в этом опросе",
    silent: "У другого человека не открыт {app} в этой переписке. Возможно, у него его нет, он не дал разрешение или закрыл его.",
    unreachable: "Сейчас до другого телефона не достучаться.",
    left: "У другого человека опрос больше не открыт.",
    outdated: "У другого человека более новая версия {app}. Обновите {app}, чтобы голосовать вместе.",
    kept: "Ваши голоса остаются на этом телефоне и объединятся с его голосами, когда у вас обоих будет открыт опрос в этой переписке.",
    liveHint: "Голоса объединяются, только пока у вас обоих открыт этот опрос в этой переписке.",
    needsChat: "Чтобы голосовать вместе, откройте {app} из переписки и разрешите ему совместную работу.",
    joinPrompt: "Другой человек открыл «{name}»",
    join: "Присоединиться",
    notNow: "Не сейчас",
    localHome: "Открыто вне переписки: эти опросы остаются на этом телефоне. Общий опрос живёт в своей переписке.",
    received: "Общий опрос",
    loading: "Ждём опрос от другого человека…",
    full: "На этом телефоне не осталось места: последние изменения не сохранены. Удалите опрос, чтобы освободить место.",
    readOnly: "Этот опрос из более новой версии {app}: обновите его, чтобы голосовать.",
    decidedDate: "Встречаемся: {day}",
    both: "({mark} оба)",
    everyone: "({mark} все)",
    some: "({mark} {yes} из {total})",
  },
  uk: {
    title: "Опитування",
    close: "Закрити",
    back: "Назад",
    kindDates: "Дати",
    kindText: "Варіанти",
    questionPlaceholder: "Питання, наприклад: Коли зустрінемося?",
    create: "Створити опитування",
    empty: "Опитувань поки немає",
    shared: "Спільне",
    closedTag: "Завершене",
    delete: "Видалити",
    confirmDelete: "Видалити «{name}» з цього телефона? Інша людина збереже свою копію.",
    cancel: "Скасувати",
    pickDays: "Торкніться днів, які пропонуєте.",
    previousMonth: "Попередній місяць",
    nextMonth: "Наступний місяць",
    addPlaceholder: "Додати варіант",
    add: "Додати",
    remove: "Прибрати",
    yes: "Мені підходить",
    maybe: "Можливо",
    no: "Мені не підходить",
    theirAnswer: "Інша людина: {answer}",
    theyHaventAnswered: "Інша людина ще не відповіла",
    goodForBoth: "Підходить обом",
    closePoll: "Завершити опитування",
    chooseHint: "Виберіть варіант, з яким опитування завершиться.",
    choose: "Вибрати",
    confirmClose: "Завершити опитування з варіантом «{option}»? Після цього ніхто не зможе голосувати.",
    onlyCreator: "Завершити опитування може лише той, хто його створив.",
    chosen: "Вибрано: {option}",
    send: "Вставити результат у чат",
    icsSave: "Зберегти в календар",
    icsSend: "Надіслати подію календаря в чат",
    icsSaved: "Збережено на цьому телефоні. Відкрийте файл, щоб додати його до календаря.",
    icsFailed: "Не вдалося зберегти файл.",
    live: "Разом",
    stopLive: "Завершити спільну роботу",
    waiting: "Чекаємо на іншу людину…",
    joined: "Разом: ви обоє в цьому опитуванні",
    silent: "Інша людина не має відкритого {app} у цій розмові. Можливо, у неї його немає, вона не дала дозволу або закрила його.",
    unreachable: "Зараз до іншого телефона не можна достукатися.",
    left: "В іншої людини опитування більше не відкрите.",
    outdated: "Інша людина має новішу версію {app}. Оновіть {app}, щоб голосувати разом.",
    kept: "Ваші голоси залишаються на цьому телефоні й об’єднаються з її голосами, коли у вас обох буде відкрите опитування в цій розмові.",
    liveHint: "Голоси об’єднуються, лише поки у вас обох відкрите це опитування в цій розмові.",
    needsChat: "Щоб голосувати разом, відкрийте {app} з розмови й дозвольте йому спільну роботу.",
    joinPrompt: "Інша людина відкрила «{name}»",
    join: "Приєднатися",
    notNow: "Не зараз",
    localHome: "Відкрито поза розмовою: ці опитування залишаються на цьому телефоні. Спільне опитування живе у своїй розмові.",
    received: "Спільне опитування",
    loading: "Чекаємо на опитування від іншої людини…",
    full: "На цьому телефоні не залишилося місця: останні зміни не збережено. Видаліть опитування, щоб звільнити місце.",
    readOnly: "Це опитування з новішої версії {app}: оновіть його, щоб голосувати.",
    decidedDate: "Зустрічаємося: {day}",
    both: "({mark} обоє)",
    everyone: "({mark} усі)",
    some: "({mark} {yes} з {total})",
  },
  tr: {
    title: "Anketler",
    close: "Kapat",
    back: "Geri",
    kindDates: "Tarihler",
    kindText: "Seçenekler",
    questionPlaceholder: "Soru, ör. Ne zaman buluşalım?",
    create: "Anketi oluştur",
    empty: "Henüz anket yok",
    shared: "Paylaşılan",
    closedTag: "Kapandı",
    delete: "Sil",
    confirmDelete: "“{name}” bu telefondan silinsin mi? Diğer kişi kendi kopyasını tutar.",
    cancel: "İptal",
    pickDays: "Önerdiğiniz günlere dokunun.",
    previousMonth: "Önceki ay",
    nextMonth: "Sonraki ay",
    addPlaceholder: "Seçenek ekle",
    add: "Ekle",
    remove: "Kaldır",
    yes: "Bana uyar",
    maybe: "Belki",
    no: "Bana uymaz",
    theirAnswer: "Diğer kişi: {answer}",
    theyHaventAnswered: "Diğer kişi henüz yanıt vermedi",
    goodForBoth: "İkinize de uyuyor",
    closePoll: "Anketi kapat",
    chooseHint: "Anketin hangi seçenekle kapanacağını seçin.",
    choose: "Seç",
    confirmClose: "Anket “{option}” ile kapatılsın mı? Bundan sonra kimse oy veremez.",
    onlyCreator: "Anketi yalnızca onu oluşturan kişi kapatabilir.",
    chosen: "Seçilen: {option}",
    send: "Sonucu sohbete koy",
    icsSave: "Takvime kaydet",
    icsSend: "Takvim etkinliğini sohbete gönder",
    icsSaved: "Bu telefona kaydedildi. Takviminize eklemek için dosyayı açın.",
    icsFailed: "Dosya kaydedilemedi.",
    live: "Canlı",
    stopLive: "Canlıyı durdur",
    waiting: "Diğer kişi bekleniyor…",
    joined: "Canlı: ikiniz de bu ankettesiniz",
    silent: "Diğer kişide bu sohbette {app} açık değil. Onda olmayabilir, izin vermemiş olabilir ya da kapatmış olabilir.",
    unreachable: "Diğer telefona şu anda ulaşılamıyor.",
    left: "Diğer kişide anket artık açık değil.",
    outdated: "Diğer kişide daha yeni bir {app} var. Birlikte oy vermek için {app} uygulamasını güncelleyin.",
    kept: "Oylarınız bu telefonda kalır ve ikiniz de anketi bu sohbette açtığınızda onunkilerle birleşir.",
    liveHint: "Canlı mod oylarınızı yalnızca ikiniz de bu anketi bu sohbette açık tuttuğunuz sürece birleştirir.",
    needsChat: "Birlikte oy vermek için {app} uygulamasını bir sohbetten açın ve canlı moda izin verin.",
    joinPrompt: "Diğer kişi “{name}” anketini açtı",
    join: "Katıl",
    notNow: "Şimdi değil",
    localHome: "Bir sohbetin dışında açıldı: bu anketler bu telefonda kalır. Paylaşılan bir anket kendi sohbetinde yaşar.",
    received: "Paylaşılan anket",
    loading: "Diğer kişiden anket bekleniyor…",
    full: "Bu telefonda yer kalmadı: son değişiklikler kaydedilmedi. Yer açmak için bir anket silin.",
    readOnly: "Bu anket daha yeni bir {app} sürümünden geliyor: oy vermek için güncelleyin.",
    decidedDate: "Buluşma günü: {day}",
    both: "({mark} ikiniz de)",
    everyone: "({mark} herkes)",
    some: "({mark} {total} kişiden {yes})",
  },
  ar: {
    title: "استطلاعات",
    close: "إغلاق",
    back: "رجوع",
    kindDates: "تواريخ",
    kindText: "خيارات",
    questionPlaceholder: "سؤال، مثلًا: متى نلتقي؟",
    create: "إنشاء الاستطلاع",
    empty: "لا توجد استطلاعات بعد",
    shared: "مشترك",
    closedTag: "مغلق",
    delete: "حذف",
    confirmDelete: "هل تحذف «{name}» من هذا الهاتف؟ يحتفظ الشخص الآخر بنسخته.",
    cancel: "إلغاء",
    pickDays: "المس الأيام التي تقترحها.",
    previousMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    addPlaceholder: "أضف خيارًا",
    add: "إضافة",
    remove: "إزالة",
    yes: "يناسبني",
    maybe: "ربما",
    no: "لا يناسبني",
    theirAnswer: "الشخص الآخر: {answer}",
    theyHaventAnswered: "لم يُجب الشخص الآخر بعد",
    goodForBoth: "يناسب كليكما",
    closePoll: "إغلاق الاستطلاع",
    chooseHint: "اختر الخيار الذي يُغلق به الاستطلاع.",
    choose: "اختيار",
    confirmClose: "هل تغلق الاستطلاع على «{option}»؟ لن يستطيع أحد التصويت بعد ذلك.",
    onlyCreator: "لا يمكن إغلاق الاستطلاع إلا لمن أنشأه.",
    chosen: "الخيار المختار: {option}",
    send: "ضع النتيجة في المحادثة",
    icsSave: "حفظ في التقويم",
    icsSend: "إرسال حدث التقويم إلى المحادثة",
    icsSaved: "حُفظ على هذا الهاتف. افتح الملف لإضافته إلى تقويمك.",
    icsFailed: "تعذّر حفظ الملف.",
    live: "مباشر",
    stopLive: "إيقاف المباشر",
    waiting: "بانتظار الشخص الآخر…",
    joined: "مباشر: أنتما الاثنان في هذا الاستطلاع",
    silent: "ليس لدى الشخص الآخر {app} مفتوحًا في هذه المحادثة. ربما لا يملكه، أو لم يمنحه الإذن، أو أغلقه.",
    unreachable: "لا يمكن الوصول إلى الهاتف الآخر الآن.",
    left: "لم يعد الاستطلاع مفتوحًا لدى الشخص الآخر.",
    outdated: "لدى الشخص الآخر إصدار أحدث من {app}. حدّث {app} لتصوّتا معًا.",
    kept: "تبقى أصواتك على هذا الهاتف وتنضم إلى أصواته عندما يكون الاستطلاع مفتوحًا لديكما في هذه المحادثة.",
    liveHint: "يجمع الوضع المباشر أصواتكما فقط ما دام هذا الاستطلاع مفتوحًا لديكما في هذه المحادثة.",
    needsChat: "للتصويت معًا، افتح {app} من محادثة مع السماح له بالوضع المباشر.",
    joinPrompt: "فتح الشخص الآخر «{name}»",
    join: "انضمام",
    notNow: "ليس الآن",
    localHome: "فُتح خارج محادثة: تبقى هذه الاستطلاعات على هذا الهاتف. الاستطلاع المشترك يبقى في محادثته.",
    received: "استطلاع مشترك",
    loading: "بانتظار الاستطلاع من الشخص الآخر…",
    full: "لا توجد مساحة كافية على هذا الهاتف: لم تُحفظ آخر التغييرات. احذف استطلاعًا لإفساح المجال.",
    readOnly: "هذا الاستطلاع من إصدار أحدث من {app}: حدّثه لتصوّت.",
    decidedDate: "نلتقي يوم {day}",
    both: "({mark} كلاكما)",
    everyone: "({mark} الجميع)",
    some: "({mark} {yes} من {total})",
  },
  hi: {
    title: "पोल",
    close: "बंद करें",
    back: "वापस",
    kindDates: "तारीखें",
    kindText: "विकल्प",
    questionPlaceholder: "सवाल, जैसे: हम कब मिलें?",
    create: "पोल बनाएँ",
    empty: "अभी कोई पोल नहीं",
    shared: "साझा",
    closedTag: "बंद",
    delete: "मिटाएँ",
    confirmDelete: "“{name}” इस फ़ोन से मिटाएँ? दूसरे व्यक्ति के पास उसकी कॉपी रहेगी।",
    cancel: "रद्द करें",
    pickDays: "जो दिन आप सुझाते हैं, उन पर टैप करें।",
    previousMonth: "पिछला महीना",
    nextMonth: "अगला महीना",
    addPlaceholder: "कोई विकल्प जोड़ें",
    add: "जोड़ें",
    remove: "हटाएँ",
    yes: "मेरे लिए ठीक है",
    maybe: "शायद",
    no: "मेरे लिए ठीक नहीं",
    theirAnswer: "दूसरा व्यक्ति: {answer}",
    theyHaventAnswered: "दूसरे व्यक्ति ने अभी जवाब नहीं दिया",
    goodForBoth: "दोनों के लिए ठीक",
    closePoll: "पोल बंद करें",
    chooseHint: "वह विकल्प चुनें जिसके साथ पोल बंद होगा।",
    choose: "चुनें",
    confirmClose: "“{option}” के साथ पोल बंद करें? उसके बाद कोई वोट नहीं कर सकेगा।",
    onlyCreator: "पोल वही बंद कर सकता है जिसने इसे बनाया।",
    chosen: "चुना गया: {option}",
    send: "नतीजा चैट में रखें",
    icsSave: "कैलेंडर में सहेजें",
    icsSend: "कैलेंडर इवेंट चैट में भेजें",
    icsSaved: "इस फ़ोन पर सहेजा गया। इसे अपने कैलेंडर में जोड़ने के लिए फ़ाइल खोलें।",
    icsFailed: "फ़ाइल सहेजी नहीं जा सकी।",
    live: "लाइव",
    stopLive: "लाइव बंद करें",
    waiting: "दूसरे व्यक्ति का इंतज़ार…",
    joined: "लाइव: आप दोनों इस पोल में हैं",
    silent: "दूसरे व्यक्ति के पास इस बातचीत में {app} खुला नहीं है। हो सकता है उनके पास यह न हो, उन्होंने अनुमति न दी हो, या इसे बंद कर दिया हो।",
    unreachable: "अभी दूसरे फ़ोन तक नहीं पहुँचा जा सकता।",
    left: "दूसरे व्यक्ति के पास अब पोल खुला नहीं है।",
    outdated: "दूसरे व्यक्ति के पास {app} का नया संस्करण है। साथ में वोट करने के लिए {app} अपडेट करें।",
    kept: "आपके वोट इस फ़ोन पर रहते हैं और जब आप दोनों इस बातचीत में पोल खोलेंगे, तब उनके वोटों से मिल जाएँगे।",
    liveHint: "लाइव आपके वोट तभी मिलाता है जब आप दोनों ने इस बातचीत में यह पोल खोल रखा हो।",
    needsChat: "साथ में वोट करने के लिए {app} को किसी बातचीत से खोलें और उसे लाइव की अनुमति दें।",
    joinPrompt: "दूसरे व्यक्ति ने “{name}” खोला",
    join: "जुड़ें",
    notNow: "अभी नहीं",
    localHome: "किसी बातचीत के बाहर खोला गया: ये पोल इसी फ़ोन पर रहते हैं। साझा किया गया पोल अपनी बातचीत में रहता है।",
    received: "साझा पोल",
    loading: "दूसरे व्यक्ति से पोल का इंतज़ार…",
    full: "इस फ़ोन पर जगह नहीं बची: आख़िरी बदलाव सहेजे नहीं गए। जगह बनाने के लिए कोई पोल मिटाएँ।",
    readOnly: "यह पोल {app} के नए संस्करण से है: वोट करने के लिए अपडेट करें।",
    decidedDate: "हम {day} को मिलेंगे",
    both: "({mark} दोनों)",
    everyone: "({mark} सभी)",
    some: "({mark} {total} में से {yes})",
  },
  bn: {
    title: "পোল",
    close: "বন্ধ",
    back: "পিছনে",
    kindDates: "তারিখ",
    kindText: "বিকল্প",
    questionPlaceholder: "প্রশ্ন, যেমন: আমরা কবে দেখা করব?",
    create: "পোল তৈরি করুন",
    empty: "এখনও কোনো পোল নেই",
    shared: "শেয়ার করা",
    closedTag: "বন্ধ হয়েছে",
    delete: "মুছুন",
    confirmDelete: "“{name}” এই ফোন থেকে মুছবেন? অন্যজনের কাছে তার কপি থাকবে।",
    cancel: "বাতিল",
    pickDays: "যে দিনগুলো প্রস্তাব করছেন সেগুলোতে ট্যাপ করুন।",
    previousMonth: "আগের মাস",
    nextMonth: "পরের মাস",
    addPlaceholder: "একটি বিকল্প যোগ করুন",
    add: "যোগ করুন",
    remove: "সরান",
    yes: "আমার সুবিধা হবে",
    maybe: "হয়তো",
    no: "আমার সুবিধা হবে না",
    theirAnswer: "অন্যজন: {answer}",
    theyHaventAnswered: "অন্যজন এখনও উত্তর দেননি",
    goodForBoth: "দুজনেরই সুবিধা",
    closePoll: "পোল বন্ধ করুন",
    chooseHint: "যে বিকল্প দিয়ে পোল বন্ধ হবে সেটি বেছে নিন।",
    choose: "বেছে নিন",
    confirmClose: "“{option}” দিয়ে পোল বন্ধ করবেন? এরপর কেউ ভোট দিতে পারবে না।",
    onlyCreator: "যিনি পোল তৈরি করেছেন শুধু তিনিই এটি বন্ধ করতে পারেন।",
    chosen: "বেছে নেওয়া হয়েছে: {option}",
    send: "ফলাফল চ্যাটে রাখুন",
    icsSave: "ক্যালেন্ডারে সংরক্ষণ করুন",
    icsSend: "ক্যালেন্ডার ইভেন্ট চ্যাটে পাঠান",
    icsSaved: "এই ফোনে সংরক্ষিত হয়েছে। আপনার ক্যালেন্ডারে যোগ করতে ফাইলটি খুলুন।",
    icsFailed: "ফাইলটি সংরক্ষণ করা যায়নি।",
    live: "লাইভ",
    stopLive: "লাইভ বন্ধ করুন",
    waiting: "অন্যজনের জন্য অপেক্ষা…",
    joined: "লাইভ: আপনারা দুজনেই এই পোলে আছেন",
    silent: "অন্যজনের এই কথোপকথনে {app} খোলা নেই। হয়তো তার কাছে এটি নেই, অনুমতি দেননি, বা বন্ধ করে রেখেছেন।",
    unreachable: "এখন অন্য ফোনে পৌঁছানো যাচ্ছে না।",
    left: "অন্যজনের কাছে পোলটি আর খোলা নেই।",
    outdated: "অন্যজনের কাছে {app}-এর নতুন সংস্করণ আছে। একসাথে ভোট দিতে {app} আপডেট করুন।",
    kept: "আপনার ভোট এই ফোনে থাকে এবং আপনারা দুজনেই এই কথোপকথনে পোলটি খুললে তার ভোটের সাথে মিলে যায়।",
    liveHint: "লাইভ আপনাদের ভোট শুধু তখনই মেলায় যখন দুজনেই এই কথোপকথনে পোলটি খুলে রাখেন।",
    needsChat: "একসাথে ভোট দিতে কোনো কথোপকথন থেকে {app} খুলুন এবং লাইভের অনুমতি দিন।",
    joinPrompt: "অন্যজন “{name}” খুলেছেন",
    join: "যোগ দিন",
    notNow: "এখন নয়",
    localHome: "কোনো কথোপকথনের বাইরে খোলা হয়েছে: এই পোলগুলো এই ফোনেই থাকে। শেয়ার করা পোল তার কথোপকথনে থাকে।",
    received: "শেয়ার করা পোল",
    loading: "অন্যজনের পোলের জন্য অপেক্ষা…",
    full: "এই ফোনে আর জায়গা নেই: শেষ পরিবর্তনগুলো সংরক্ষিত হয়নি। জায়গা করতে একটি পোল মুছুন।",
    readOnly: "এই পোলটি {app}-এর নতুন সংস্করণ থেকে এসেছে: ভোট দিতে আপডেট করুন।",
    decidedDate: "আমরা দেখা করছি {day}",
    both: "({mark} দুজনেই)",
    everyone: "({mark} সবাই)",
    some: "({mark} {total} জনের মধ্যে {yes})",
  },
  id: {
    title: "Polling",
    close: "Tutup",
    back: "Kembali",
    kindDates: "Tanggal",
    kindText: "Pilihan",
    questionPlaceholder: "Pertanyaan, mis. Kapan kita ketemu?",
    create: "Buat polling",
    empty: "Belum ada polling",
    shared: "Dibagikan",
    closedTag: "Ditutup",
    delete: "Hapus",
    confirmDelete: "Hapus “{name}” dari ponsel ini? Orang lain tetap menyimpan salinannya.",
    cancel: "Batal",
    pickDays: "Ketuk hari-hari yang Anda usulkan.",
    previousMonth: "Bulan sebelumnya",
    nextMonth: "Bulan berikutnya",
    addPlaceholder: "Tambah pilihan",
    add: "Tambah",
    remove: "Buang",
    yes: "Saya bisa",
    maybe: "Mungkin",
    no: "Saya tidak bisa",
    theirAnswer: "Orang lain: {answer}",
    theyHaventAnswered: "Orang lain belum menjawab",
    goodForBoth: "Cocok untuk berdua",
    closePoll: "Tutup polling",
    chooseHint: "Pilih opsi yang menutup polling.",
    choose: "Pilih",
    confirmClose: "Tutup polling dengan “{option}”? Setelah itu tidak ada yang bisa memilih.",
    onlyCreator: "Hanya pembuat polling yang bisa menutupnya.",
    chosen: "Terpilih: {option}",
    send: "Taruh hasilnya di obrolan",
    icsSave: "Simpan ke kalender",
    icsSend: "Kirim acara kalender ke obrolan",
    icsSaved: "Tersimpan di ponsel ini. Buka file-nya untuk menambahkannya ke kalender Anda.",
    icsFailed: "File tidak dapat disimpan.",
    live: "Langsung",
    stopLive: "Hentikan mode langsung",
    waiting: "Menunggu orang lain…",
    joined: "Langsung: kalian berdua ada di polling ini",
    silent: "Orang lain tidak membuka {app} di percakapan ini. Mungkin dia tidak memilikinya, tidak memberi izin, atau sudah menutupnya.",
    unreachable: "Ponsel lain tidak dapat dijangkau sekarang.",
    left: "Orang lain sudah tidak membuka polling ini.",
    outdated: "Orang lain punya {app} versi lebih baru. Perbarui {app} untuk memilih bersama.",
    kept: "Suara Anda tetap di ponsel ini dan bergabung dengan suaranya saat kalian berdua membuka polling di percakapan ini.",
    liveHint: "Mode langsung menggabungkan suara kalian hanya selama kalian berdua membuka polling ini di percakapan ini.",
    needsChat: "Untuk memilih bersama, buka {app} dari sebuah percakapan dan izinkan mode langsung.",
    joinPrompt: "Orang lain membuka “{name}”",
    join: "Gabung",
    notNow: "Nanti",
    localHome: "Dibuka di luar percakapan: polling ini tetap di ponsel ini. Polling yang dibagikan ada di percakapannya.",
    received: "Polling yang dibagikan",
    loading: "Menunggu polling dari orang lain…",
    full: "Ruang di ponsel ini habis: perubahan terakhir belum tersimpan. Hapus sebuah polling untuk memberi ruang.",
    readOnly: "Polling ini berasal dari {app} versi lebih baru: perbarui untuk memilih.",
    decidedDate: "Kita ketemu {day}",
    both: "({mark} berdua)",
    everyone: "({mark} semua)",
    some: "({mark} {yes} dari {total})",
  },
  vi: {
    title: "Bình chọn",
    close: "Đóng",
    back: "Quay lại",
    kindDates: "Ngày",
    kindText: "Lựa chọn",
    questionPlaceholder: "Câu hỏi, ví dụ: Khi nào mình gặp nhau?",
    create: "Tạo bình chọn",
    empty: "Chưa có bình chọn nào",
    shared: "Đã chia sẻ",
    closedTag: "Đã đóng",
    delete: "Xóa",
    confirmDelete: "Xóa “{name}” khỏi điện thoại này? Người kia vẫn giữ bản của họ.",
    cancel: "Hủy",
    pickDays: "Chạm vào những ngày bạn đề xuất.",
    previousMonth: "Tháng trước",
    nextMonth: "Tháng sau",
    addPlaceholder: "Thêm một lựa chọn",
    add: "Thêm",
    remove: "Bỏ",
    yes: "Tôi được",
    maybe: "Có thể",
    no: "Tôi không được",
    theirAnswer: "Người kia: {answer}",
    theyHaventAnswered: "Người kia chưa trả lời",
    goodForBoth: "Cả hai đều được",
    closePoll: "Đóng bình chọn",
    chooseHint: "Chọn phương án để đóng bình chọn.",
    choose: "Chọn",
    confirmClose: "Đóng bình chọn với “{option}”? Sau đó không ai bình chọn được nữa.",
    onlyCreator: "Chỉ người tạo bình chọn mới đóng được.",
    chosen: "Đã chọn: {option}",
    send: "Đưa kết quả vào cuộc trò chuyện",
    icsSave: "Lưu vào lịch",
    icsSend: "Gửi sự kiện lịch vào cuộc trò chuyện",
    icsSaved: "Đã lưu trên điện thoại này. Mở tệp để thêm vào lịch của bạn.",
    icsFailed: "Không lưu được tệp.",
    live: "Trực tiếp",
    stopLive: "Dừng trực tiếp",
    waiting: "Đang chờ người kia…",
    joined: "Trực tiếp: cả hai đang ở bình chọn này",
    silent: "Người kia chưa mở {app} trong cuộc trò chuyện này. Có thể họ không có, chưa cho phép, hoặc đã đóng nó.",
    unreachable: "Hiện không liên lạc được với điện thoại kia.",
    left: "Người kia không còn mở bình chọn này nữa.",
    outdated: "Người kia có {app} mới hơn. Hãy cập nhật {app} để cùng bình chọn.",
    kept: "Phiếu của bạn vẫn ở trên điện thoại này và sẽ gộp với của họ khi cả hai cùng mở bình chọn trong cuộc trò chuyện này.",
    liveHint: "Chế độ trực tiếp chỉ gộp phiếu khi cả hai đang mở bình chọn này trong cuộc trò chuyện này.",
    needsChat: "Để cùng bình chọn, hãy mở {app} từ một cuộc trò chuyện và cho phép chế độ trực tiếp.",
    joinPrompt: "Người kia đã mở “{name}”",
    join: "Tham gia",
    notNow: "Để sau",
    localHome: "Mở bên ngoài cuộc trò chuyện: các bình chọn này chỉ ở trên điện thoại này. Bình chọn được chia sẻ nằm trong cuộc trò chuyện của nó.",
    received: "Bình chọn được chia sẻ",
    loading: "Đang chờ bình chọn từ người kia…",
    full: "Điện thoại này hết chỗ: các thay đổi mới nhất chưa được lưu. Hãy xóa một bình chọn để có chỗ.",
    readOnly: "Bình chọn này đến từ {app} mới hơn: hãy cập nhật để bình chọn.",
    decidedDate: "Hẹn gặp vào {day}",
    both: "({mark} cả hai)",
    everyone: "({mark} mọi người)",
    some: "({mark} {yes}/{total})",
  },
  th: {
    title: "โพล",
    close: "ปิด",
    back: "กลับ",
    kindDates: "วันที่",
    kindText: "ตัวเลือก",
    questionPlaceholder: "คำถาม เช่น เราจะเจอกันเมื่อไหร่",
    create: "สร้างโพล",
    empty: "ยังไม่มีโพล",
    shared: "แชร์แล้ว",
    closedTag: "ปิดแล้ว",
    delete: "ลบ",
    confirmDelete: "ลบ “{name}” ออกจากโทรศัพท์นี้ไหม อีกฝ่ายยังมีสำเนาของตัวเอง",
    cancel: "ยกเลิก",
    pickDays: "แตะวันที่คุณเสนอ",
    previousMonth: "เดือนก่อน",
    nextMonth: "เดือนถัดไป",
    addPlaceholder: "เพิ่มตัวเลือก",
    add: "เพิ่ม",
    remove: "เอาออก",
    yes: "ฉันสะดวก",
    maybe: "อาจจะ",
    no: "ฉันไม่สะดวก",
    theirAnswer: "อีกฝ่าย: {answer}",
    theyHaventAnswered: "อีกฝ่ายยังไม่ได้ตอบ",
    goodForBoth: "สะดวกทั้งคู่",
    closePoll: "ปิดโพล",
    chooseHint: "เลือกตัวเลือกที่จะใช้ปิดโพล",
    choose: "เลือก",
    confirmClose: "ปิดโพลด้วย “{option}” ไหม หลังจากนั้นจะไม่มีใครโหวตได้",
    onlyCreator: "เฉพาะคนที่สร้างโพลเท่านั้นที่ปิดโพลได้",
    chosen: "เลือกแล้ว: {option}",
    send: "ใส่ผลลัพธ์ลงในแชท",
    icsSave: "บันทึกลงปฏิทิน",
    icsSend: "ส่งกิจกรรมปฏิทินไปที่แชท",
    icsSaved: "บันทึกในโทรศัพท์นี้แล้ว เปิดไฟล์เพื่อเพิ่มลงในปฏิทินของคุณ",
    icsFailed: "บันทึกไฟล์ไม่ได้",
    live: "เรียลไทม์",
    stopLive: "หยุดเรียลไทม์",
    waiting: "กำลังรออีกฝ่าย…",
    joined: "เรียลไทม์: คุณทั้งสองอยู่ในโพลนี้",
    silent: "อีกฝ่ายไม่ได้เปิด {app} ในการสนทนานี้ อาจไม่มีแอปนี้ ไม่ได้อนุญาต หรือปิดไปแล้ว",
    unreachable: "ตอนนี้ติดต่อโทรศัพท์อีกเครื่องไม่ได้",
    left: "อีกฝ่ายไม่ได้เปิดโพลนี้อยู่แล้ว",
    outdated: "อีกฝ่ายมี {app} เวอร์ชันใหม่กว่า อัปเดต {app} เพื่อโหวตด้วยกัน",
    kept: "โหวตของคุณอยู่ในโทรศัพท์นี้ และจะรวมกับของอีกฝ่ายเมื่อทั้งสองเปิดโพลในการสนทนานี้",
    liveHint: "โหมดเรียลไทม์รวมโหวตเฉพาะตอนที่ทั้งสองเปิดโพลนี้ในการสนทนานี้",
    needsChat: "หากต้องการโหวตด้วยกัน ให้เปิด {app} จากการสนทนาและอนุญาตโหมดเรียลไทม์",
    joinPrompt: "อีกฝ่ายเปิด “{name}”",
    join: "เข้าร่วม",
    notNow: "ไว้ทีหลัง",
    localHome: "เปิดนอกการสนทนา: โพลเหล่านี้อยู่ในโทรศัพท์นี้เท่านั้น โพลที่แชร์จะอยู่ในการสนทนาของมัน",
    received: "โพลที่แชร์",
    loading: "กำลังรอโพลจากอีกฝ่าย…",
    full: "โทรศัพท์นี้ไม่มีที่ว่างแล้ว: การเปลี่ยนแปลงล่าสุดยังไม่ได้บันทึก ลบโพลหนึ่งเพื่อเพิ่มที่ว่าง",
    readOnly: "โพลนี้มาจาก {app} เวอร์ชันใหม่กว่า: อัปเดตเพื่อโหวต",
    decidedDate: "เจอกัน{day}",
    both: "({mark} ทั้งคู่)",
    everyone: "({mark} ทุกคน)",
    some: "({mark} {yes} จาก {total})",
  },
  ja: {
    title: "投票",
    close: "閉じる",
    back: "戻る",
    kindDates: "日程",
    kindText: "選択肢",
    questionPlaceholder: "質問（例：いつ会う？）",
    create: "投票を作成",
    empty: "まだ投票はありません",
    shared: "共有中",
    closedTag: "締め切り済み",
    delete: "削除",
    confirmDelete: "「{name}」をこの電話から削除しますか？相手のコピーは残ります。",
    cancel: "キャンセル",
    pickDays: "提案する日をタップしてください。",
    previousMonth: "前の月",
    nextMonth: "次の月",
    addPlaceholder: "選択肢を追加",
    add: "追加",
    remove: "削除する",
    yes: "都合がいい",
    maybe: "たぶん",
    no: "都合が悪い",
    theirAnswer: "相手：{answer}",
    theyHaventAnswered: "相手はまだ答えていません",
    goodForBoth: "二人とも都合がいい",
    closePoll: "投票を締め切る",
    chooseHint: "投票を締め切るときの選択肢を選んでください。",
    choose: "選ぶ",
    confirmClose: "「{option}」で投票を締め切りますか？その後は誰も投票できません。",
    onlyCreator: "投票を締め切れるのは作成した人だけです。",
    chosen: "決定：{option}",
    send: "結果をチャットに入れる",
    icsSave: "カレンダーに保存",
    icsSend: "カレンダーの予定をチャットに送る",
    icsSaved: "この電話に保存しました。ファイルを開いてカレンダーに追加してください。",
    icsFailed: "ファイルを保存できませんでした。",
    live: "ライブ",
    stopLive: "ライブを終了",
    waiting: "相手を待っています…",
    joined: "ライブ：二人ともこの投票にいます",
    silent: "相手はこの会話で {app} を開いていません。持っていない、許可していない、または閉じている可能性があります。",
    unreachable: "今は相手の電話に届きません。",
    left: "相手はもうこの投票を開いていません。",
    outdated: "相手の {app} のほうが新しいバージョンです。一緒に投票するには {app} を更新してください。",
    kept: "あなたの投票はこの電話に残り、二人ともこの会話で投票を開いたときに相手の投票とまとまります。",
    liveHint: "ライブで投票がまとまるのは、二人ともこの会話でこの投票を開いている間だけです。",
    needsChat: "一緒に投票するには、会話から {app} を開き、ライブを許可してください。",
    joinPrompt: "相手が「{name}」を開きました",
    join: "参加",
    notNow: "今はしない",
    localHome: "会話の外で開いています：これらの投票はこの電話にだけ残ります。共有した投票はその会話の中にあります。",
    received: "共有された投票",
    loading: "相手からの投票を待っています…",
    full: "この電話に空きがありません：最新の変更は保存されていません。投票を削除して空きを作ってください。",
    readOnly: "この投票は新しいバージョンの {app} で作られています：投票するには更新してください。",
    decidedDate: "{day}に会いましょう",
    both: "（{mark} 二人とも）",
    everyone: "（{mark} 全員）",
    some: "（{mark} {total}人中{yes}人）",
  },
  ko: {
    title: "투표",
    close: "닫기",
    back: "뒤로",
    kindDates: "날짜",
    kindText: "선택지",
    questionPlaceholder: "질문, 예: 언제 만날까요?",
    create: "투표 만들기",
    empty: "아직 투표가 없습니다",
    shared: "공유됨",
    closedTag: "마감됨",
    delete: "삭제",
    confirmDelete: "“{name}”을(를) 이 휴대폰에서 삭제할까요? 상대방은 자신의 사본을 그대로 가집니다.",
    cancel: "취소",
    pickDays: "제안할 날짜를 누르세요.",
    previousMonth: "이전 달",
    nextMonth: "다음 달",
    addPlaceholder: "선택지 추가",
    add: "추가",
    remove: "빼기",
    yes: "괜찮아요",
    maybe: "아마도",
    no: "안 돼요",
    theirAnswer: "상대방: {answer}",
    theyHaventAnswered: "상대방이 아직 답하지 않았습니다",
    goodForBoth: "둘 다 괜찮음",
    closePoll: "투표 마감",
    chooseHint: "투표를 마감할 선택지를 고르세요.",
    choose: "고르기",
    confirmClose: "“{option}”(으)로 투표를 마감할까요? 그 뒤에는 아무도 투표할 수 없습니다.",
    onlyCreator: "투표를 만든 사람만 마감할 수 있습니다.",
    chosen: "결정: {option}",
    send: "결과를 채팅에 넣기",
    icsSave: "캘린더에 저장",
    icsSend: "캘린더 일정을 채팅으로 보내기",
    icsSaved: "이 휴대폰에 저장했습니다. 파일을 열어 캘린더에 추가하세요.",
    icsFailed: "파일을 저장할 수 없습니다.",
    live: "실시간",
    stopLive: "실시간 끝내기",
    waiting: "상대방을 기다리는 중…",
    joined: "실시간: 두 사람 모두 이 투표에 있습니다",
    silent: "상대방이 이 대화에서 {app}을(를) 열지 않았습니다. 앱이 없거나, 허용하지 않았거나, 닫았을 수 있습니다.",
    unreachable: "지금은 상대방 휴대폰에 연결할 수 없습니다.",
    left: "상대방이 더 이상 이 투표를 열어 두고 있지 않습니다.",
    outdated: "상대방의 {app}이(가) 더 새 버전입니다. 함께 투표하려면 {app}을(를) 업데이트하세요.",
    kept: "내 투표는 이 휴대폰에 남아 있다가, 두 사람 모두 이 대화에서 투표를 열면 상대방의 투표와 합쳐집니다.",
    liveHint: "실시간 모드는 두 사람 모두 이 대화에서 이 투표를 열어 둔 동안에만 투표를 합칩니다.",
    needsChat: "함께 투표하려면 대화에서 {app}을(를) 열고 실시간을 허용하세요.",
    joinPrompt: "상대방이 “{name}”을(를) 열었습니다",
    join: "참여",
    notNow: "나중에",
    localHome: "대화 밖에서 열었습니다: 이 투표들은 이 휴대폰에만 남습니다. 공유한 투표는 그 대화 안에 있습니다.",
    received: "공유된 투표",
    loading: "상대방의 투표를 기다리는 중…",
    full: "이 휴대폰에 공간이 없습니다: 최근 변경 내용이 저장되지 않았습니다. 투표를 삭제해 공간을 만드세요.",
    readOnly: "이 투표는 더 새 버전의 {app}에서 왔습니다: 투표하려면 업데이트하세요.",
    decidedDate: "{day}에 만나요",
    both: "({mark} 둘 다)",
    everyone: "({mark} 모두)",
    some: "({mark} {total}명 중 {yes}명)",
  },
  "zh-CN": {
    title: "投票",
    close: "关闭",
    back: "返回",
    kindDates: "日期",
    kindText: "选项",
    questionPlaceholder: "问题，例如：我们什么时候见面？",
    create: "创建投票",
    empty: "还没有投票",
    shared: "已共享",
    closedTag: "已结束",
    delete: "删除",
    confirmDelete: "要从这台手机删除“{name}”吗？对方会保留自己的副本。",
    cancel: "取消",
    pickDays: "点按你提议的日期。",
    previousMonth: "上个月",
    nextMonth: "下个月",
    addPlaceholder: "添加选项",
    add: "添加",
    remove: "移除",
    yes: "我可以",
    maybe: "也许",
    no: "我不行",
    theirAnswer: "对方：{answer}",
    theyHaventAnswered: "对方还没有回答",
    goodForBoth: "你们俩都可以",
    closePoll: "结束投票",
    chooseHint: "选择用来结束投票的选项。",
    choose: "选择",
    confirmClose: "要以“{option}”结束投票吗？之后谁都不能再投票。",
    onlyCreator: "只有创建投票的人才能结束它。",
    chosen: "已选定：{option}",
    send: "把结果放进聊天",
    icsSave: "保存到日历",
    icsSend: "把日历活动发送到聊天",
    icsSaved: "已保存在这台手机上。打开文件即可添加到你的日历。",
    icsFailed: "无法保存文件。",
    live: "实时",
    stopLive: "停止实时",
    waiting: "正在等待对方…",
    joined: "实时：你们都在这个投票里",
    silent: "对方没有在这个对话中打开 {app}。对方可能没有安装、没有授权，或已经关闭。",
    unreachable: "现在无法连接到对方的手机。",
    left: "对方已不再打开这个投票。",
    outdated: "对方的 {app} 版本更新。请更新 {app} 以便一起投票。",
    kept: "你的投票会保留在这台手机上，等你们俩都在这个对话中打开投票时再与对方的合并。",
    liveHint: "只有你们俩都在这个对话中打开这个投票时，实时模式才会合并投票。",
    needsChat: "要一起投票，请从对话中打开 {app}，并允许实时功能。",
    joinPrompt: "对方打开了“{name}”",
    join: "加入",
    notNow: "以后再说",
    localHome: "在对话之外打开：这些投票只保留在这台手机上。共享的投票留在它的对话里。",
    received: "共享的投票",
    loading: "正在等待对方的投票…",
    full: "这台手机没有空间了：最近的更改没有保存。删除一个投票以腾出空间。",
    readOnly: "这个投票来自更新版本的 {app}：请更新后再投票。",
    decidedDate: "我们{day}见",
    both: "（{mark} 两人都可以）",
    everyone: "（{mark} 所有人）",
    some: "（{mark} {total} 人中 {yes} 人）",
  },
  "zh-TW": {
    title: "投票",
    close: "關閉",
    back: "返回",
    kindDates: "日期",
    kindText: "選項",
    questionPlaceholder: "問題，例如：我們什麼時候見面？",
    create: "建立投票",
    empty: "還沒有投票",
    shared: "已共享",
    closedTag: "已結束",
    delete: "刪除",
    confirmDelete: "要從這支手機刪除「{name}」嗎？對方會保留自己的副本。",
    cancel: "取消",
    pickDays: "點按你提議的日期。",
    previousMonth: "上個月",
    nextMonth: "下個月",
    addPlaceholder: "新增選項",
    add: "新增",
    remove: "移除",
    yes: "我可以",
    maybe: "也許",
    no: "我不行",
    theirAnswer: "對方：{answer}",
    theyHaventAnswered: "對方還沒有回答",
    goodForBoth: "你們都可以",
    closePoll: "結束投票",
    chooseHint: "選擇用來結束投票的選項。",
    choose: "選擇",
    confirmClose: "要以「{option}」結束投票嗎？之後誰都不能再投票。",
    onlyCreator: "只有建立投票的人才能結束它。",
    chosen: "已選定：{option}",
    send: "把結果放進聊天",
    icsSave: "儲存到行事曆",
    icsSend: "把行事曆活動傳送到聊天",
    icsSaved: "已儲存在這支手機上。開啟檔案即可加入你的行事曆。",
    icsFailed: "無法儲存檔案。",
    live: "即時",
    stopLive: "停止即時",
    waiting: "正在等待對方…",
    joined: "即時：你們都在這個投票裡",
    silent: "對方沒有在這個對話中開啟 {app}。對方可能沒有安裝、沒有授權，或已經關閉。",
    unreachable: "現在無法連線到對方的手機。",
    left: "對方已不再開啟這個投票。",
    outdated: "對方的 {app} 版本較新。請更新 {app} 以便一起投票。",
    kept: "你的投票會保留在這支手機上，等你們都在這個對話中開啟投票時再與對方的合併。",
    liveHint: "只有你們都在這個對話中開啟這個投票時，即時模式才會合併投票。",
    needsChat: "要一起投票，請從對話中開啟 {app}，並允許即時功能。",
    joinPrompt: "對方開啟了「{name}」",
    join: "加入",
    notNow: "稍後再說",
    localHome: "在對話之外開啟：這些投票只保留在這支手機上。共享的投票留在它的對話裡。",
    received: "共享的投票",
    loading: "正在等待對方的投票…",
    full: "這支手機沒有空間了：最近的變更沒有儲存。刪除一個投票以騰出空間。",
    readOnly: "這個投票來自較新版本的 {app}：請更新後再投票。",
    decidedDate: "我們{day}見",
    both: "（{mark} 兩人都可以）",
    everyone: "（{mark} 所有人）",
    some: "（{mark} {total} 人中 {yes} 人）",
  },
};
